# Generated by Django 5.0.6 on 2024-06-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='destinos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta', models.BooleanField(default=False)),
            ],
        ),
    ]
