# Generated by Django 5.0.6 on 2024-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoturistico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
